### ISSUE TITLE
Error Code 400

### ISSUE THREAD

**Issue by slavakurilyak** [gsaivinay/claude-prompt-optimizer#1]
It would be great to catch silent errors like

> Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Your credit balance is too low to access the Claude API. Please go to Plans & Billing to upgrade or purchase credits.'}}

when calling `CLIENT.messages.create`

**Comment by gsaivinay** [comment]
Hello @slavakurilyak - thanks for the issue.

Vercel AI SDK is able to catch Anthropic `completion` API errors, but it is not playing nice with Anthropic `messages` API errors. This is now handled.

I must use Anthropic  `messages` API as `Claude 3 Sonnet` will not work with `completion` API

Hope this is clear. Let me know if anything else is needed.

![image](https://github.com/gsaivinay/claude-prompt-optimizer/assets/9410663/8d95ff92-14f6-4f76-bed2-a676673f427a)
